### ISSUE TITLE
CSYNC installation

### ISSUE THREAD

**Issue by bodgit** [borti4938/SNES-AddOn-PCBs#11]
Hello,

I have one of the new mod boards with the De-Jitter CSYNC output for a PAL SNSP-CPU-01 SNES and I had some questions about wiring the CSYNC "/CS.o buf" signal to the multi-out:

1. I currently have an RGB SCART cable that contains an LM1881 sync stripper that generates CSYNC from the composite video on pin 9 of the multi-out. Would this still work okay without needing to wire up the buffered CSYNC from the mod board?
2. If I _do_ need to wire up the buffered CSYNC and choose to wire it to pin 3, (as that would mean an NTSC cable would Just Work), what is the easiest way to disable the 12V that is normally wired to that pin on the PAL systems? Is there a specific component that should be removed?

Thanks

**Comment by borti4938** [comment]
1. yes, no modification needed (although I still do not understand the purpose of sync stripper build in cables)
2. 3Chip-PAL: remove R72 (just by schematic, never tested by myself, please double check by your own!!!),1Chip-PAL: remove R28
