### ISSUE TITLE
BOM Missing Values for S-Vid

### ISSUE THREAD

**Issue by Slypty** [borti4938/SNES-AddOn-PCBs#12]
Having the SNES_RGB Amp w/ CSync and SVid made, but no info on the BOM list for the SVID values.  Would be grateful for an update soon, thanks!

**Comment by borti4938** [comment]
don't know where the problem is. It's in the excel sheet (last page named SNES_RGBAmp_wCSYNC_SVid)

**Comment by Slypty** [comment]
Appreciate it.
