### ISSUE TITLE
RGB Bypass BOM error

### ISSUE THREAD

**Issue by arithmaldor** [borti4938/SNES-AddOn-PCBs#6]
In the "Notes" column, the suggestions for which resistors to use to resolve the brightness issue has the systems swapped; 1.2kOhm suggested for the SNES2 and 750Ohm for the 1Chip instead of vice versa. Attached is a corrected version.
[BOM_SNES_RGB_bypass.xlsx](https://github.com/borti4938/SNES-AddOn-PCBs/files/1921016/BOM_SNES_RGB_bypass.xlsx)

**Comment by borti4938** [comment]
thank you for pointing out. At least in the readme it was in the correct order. BOM fixed with 8b699e7a86008093aa463da4faeab3346c08a853
