### ISSUE TITLE
Possible overlapping on JTAG- Pads?

### ISSUE THREAD

**Issue by DevLaTron** [borti4938/SNES-AddOn-PCBs#7]
Hey,

after importing the Schematics/Board into KiCAD 5, I'm getting overlapping of the 3.3V line with GND and TMS. It looks awfully close looking at it on screen, and I don't think 3.3V to GND is the best of ideas there.

The GND via next to I2C SDA1 also seems a bit close.

Depending on the constraints/accuracy of the Manufacturer, could this lead to issues?

**Comment by borti4938** [comment]
Actually I don't know how KiCad evaluates planes during import and afterwards during design. You might have to adjust clearance rules or something like that, Also take a look into the restring settings for the via. However, there are some traces / vias which are closer to other signals that the ones you pointed out. Maybe this might be an import issue with latest EAGLE version incompatibility.

Clearence is set to 0.2mm (8mil): [see desing file](https://github.com/borti4938/SNES-AddOn-PCBs/blob/master/MultiRegion_with_DeJitter_QID/SNES_MR_DeJitter_QID.brd#L2044) DRC does not output any clearence issues and I have the previous version produced and tested without any problems. Last change was removing two traces as they were not needed anymore with latest firmware changes.

To the best of my knowledge most prototype services have 6mil capability without any extra costs and some suggest 8mil to be save. So everything should be good.

**Comment by DevLaTron** [comment]
I just rechecked. Clearance is 0.2.

It's def. the import, then:

(This one is evil, actually)
https://i.imgur.com/PdQdYI2.png

(Just clearance, should be fine)
https://i.imgur.com/2AFNFSz.png

It's probably just an issue for people that can't use your gerber files. For some reason JLCPCB doesn't like the ones you provided, so I had to plot my own.

I did reroute that a tiny bit and ordered some, so test incoming. ;)

Thanks for your great work (again) btw.

**Comment by borti4938** [comment]
Ah, I see. The import changes the pad shape from octagon to square. Now I understand both issues. If you can reroute or reshape it, it will be great :)

Have you tried to send the OSHPark legacy gerbers to JLCPCB? OSHPark also does not like the newer EAGLE gerber outputs.

**Comment by DevLaTron** [comment]
Yeah, the newer ones won't work on JLCPCB. It gets stuck analysing at 92%, which if I remember correctly could be an outline or drill file issue.

The legacy ones work, I'm not sure if "legacy" is a good name for the folder, maybe add "_format" ?. ;)

Ordered and in production. Now to scour through Mouser. ;)
