### ISSUE TITLE
Some question about the Classic Multiregion Mod (QID?) 

### ISSUE THREAD

**Issue by 0C-34** [borti4938/SNES-AddOn-PCBs#8]
I wanted to do the Classic Multiregion Mod QID but I'm having problems finding a 21.477273MHz crystal in Europe and I find only 21MHz one (without looking on ebay where they cost 5 times the 17.etcMHz one and prob takes 5 times the shipping time) so **I wanted to ask what tolerance it should have**.

Also, **which chip i should use for the supercic**? The 12F629 seems to have 2 firmwares (**which firmware should i use**? I can't find any documentation about the difference) both newer, but I can't find any way to assembly the asm file (I've tried mplab, maybe **i need some help on how to setup the assembler enviroment**) so maybe i should stuck to the older already compiled hex from another site?

One last thing: I plan on using my 1Chip SNES with Sony Trinitron (SCART input) and i plan doing the rgb mod on the snes at some point probably, **there is any concrete advantage on the newer MultiRegion board with the Dejitter** worth the trouble of buying 2 extra programmer for it? (I already have the pickit3)

I have no other issues other that these, sorry if I sound obnoxious and/or noob-ish but I've never ever worked with Assembly code until now and I feel also a bit lost with the quantity of options ':D

**Comment by borti4938** [comment]
1. Get as close to the 21.477273MHz as possible with lowest tolerance in ppm as possible. They are very hard to find. I personally bought them on Aliexpress.
2. There is no 12F629 on the board. You need a 16F630 with SuperCIC-lock firmware on it. Get the fw on sd2snes.de, it's precompiled.
3. Newer MultiRegion mod does not need to source the 21.477273MHz crystal e.g. Electrically, the design is better.

**Comment by 0C-34** [comment]
ok, thanks! when i'll have the time to check my budget i'll decide between the two :)
