### ISSUE TITLE
Super cic install problems

### ISSUE THREAD

**Issue by beanyboo** [borti4938/SNES-AddOn-PCBs#9]
Not sure if this is the right place to post this.

I have followed the instructions on fitting the SuperCIC AIO with DFO and DeJitter.

The console powers on and the led will cycle though it's colors when holding the reset button.

Unfortunately there isn't any picture display.

Any advice would be appreciated

**Comment by borti4938** [comment]
A black screen is often caused by a bad connection between modding board and cartridge slot. Try to reflow the solder here.
